# Neural Network Experiments

## Experiment 1 — Hidden Layer Size

I'm testing different numbers of neurons in the hidden layer to see how they affect model performance.

### 10 neurons
Accuracy: 78.21%
Precision: 79.66%
Recall: 63.51%
F1 Score: 70.68%

### 16 neurons
Accuracy: 79.33%
Precision: 75.34%
Recall: 74.32%
F1 Score: 74.83%

### 32 neurons
Accuracy: 78.77%
Precision: 75.00%
Recall: 72.97%
F1 Score: 73.97%

### Conclusion
Increasing the hidden layer size from 10 to 16 neurons improved the overall model performance. The F1 Score increased from 70.68% to 74.83%, while recall increased from 63.51% to 74.32%.

Increasing the hidden layer further to 32 neurons did not improve the results. Its F1 Score was 73.97%, slightly lower than the 16-neuron model.

The 16-neuron model performed best overall, suggesting that increasing the number of neurons initially helped the network learn the classification task, but adding more neurons did not necessarily improve performance.

In [5]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath("../src"))

from models.neural_network import NeuralNetwork
from utils.metrics import accuracy, precision, recall, f1_score
from utils.preprocessing import preprocessing_data

X_train, X_test, y_train, y_test = preprocessing_data("../data/train.csv")


### 10 Neurons - Baseline

In [6]:
np.random.seed(42)

network = NeuralNetwork(
    input_size=4,
    hidden_size=10,
    learning_rate=0.01
)

losses = network.train(
    X_train,
    y_train,
    epochs=1000,
    print_every=50
)

predictions = network.forward(X_test)
predictions = (predictions >= 0.5).astype(int)

print(f"Accuracy: {accuracy(y_test, predictions) * 100:.2f}%")
print(f"Precision: {precision(y_test, predictions) * 100:.2f}%")
print(f"Recall: {recall(y_test, predictions) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, predictions) * 100:.2f}%")

Epoch 0, loss 1.2164
Epoch 50, loss 0.9158
Epoch 100, loss 0.7704
Epoch 150, loss 0.6951
Epoch 200, loss 0.6470
Epoch 250, loss 0.6119
Epoch 300, loss 0.5848
Epoch 350, loss 0.5630
Epoch 400, loss 0.5454
Epoch 450, loss 0.5310
Epoch 500, loss 0.5191
Converged at epoch 520
Accuracy: 78.21%
Precision: 79.66%
Recall: 63.51%
F1 Score: 70.68%


### 16 Neurons - Baseline

In [7]:
np.random.seed(42)

network = NeuralNetwork(
    input_size=4,
    hidden_size=16,
    learning_rate=0.01
)

losses = network.train(
    X_train,
    y_train,
    epochs=1000,
    print_every=50
)

predictions = network.forward(X_test)
predictions = (predictions >= 0.5).astype(int)

print(f"Accuracy: {accuracy(y_test, predictions) * 100:.2f}%")
print(f"Precision: {precision(y_test, predictions) * 100:.2f}%")
print(f"Recall: {recall(y_test, predictions) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, predictions) * 100:.2f}%")

Epoch 0, loss 0.8232
Epoch 50, loss 0.6671
Epoch 100, loss 0.5872
Epoch 150, loss 0.5431
Epoch 200, loss 0.5169
Epoch 250, loss 0.5003
Converged at epoch 294
Accuracy: 79.33%
Precision: 75.34%
Recall: 74.32%
F1 Score: 74.83%


### 32 Neurons - Baseline

In [8]:
np.random.seed(42)

network = NeuralNetwork(
    input_size=4,
    hidden_size=32,
    learning_rate=0.01
)

losses = network.train(
    X_train,
    y_train,
    epochs=1000,
    print_every=50
)

predictions = network.forward(X_test)
predictions = (predictions >= 0.5).astype(int)

print(f"Accuracy: {accuracy(y_test, predictions) * 100:.2f}%")
print(f"Precision: {precision(y_test, predictions) * 100:.2f}%")
print(f"Recall: {recall(y_test, predictions) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, predictions) * 100:.2f}%")

Epoch 0, loss 0.7014
Epoch 50, loss 0.6039
Epoch 100, loss 0.5503
Epoch 150, loss 0.5185
Epoch 200, loss 0.4983
Epoch 250, loss 0.4846
Converged at epoch 273
Accuracy: 78.77%
Precision: 75.00%
Recall: 72.97%
F1 Score: 73.97%


## Experiment 2 - Learning Rate

I'm testing different learning rates to see how they affect the training process and final model performance.

The hidden layer will use 16 neurons based on the results from experiment 1.

Learning rates tested:
- 0.001
- 0.01
- 0.05

### Results
| Learning Rate | Accuracy | Precision | Recall | F1 Score |
|---:|---:|---:|---:|---:|
| 0.001 | 58.66% | 50.00% | 48.65% | 49.32% |
| 0.01 | 79.33% | 75.34% | 74.32% | 74.83% |
| 0.05 | 78.21% | 74.65% | 71.62% | 73.10% |

### Conclusion

The learning rate of 0.01 produced the best overall performance, achieving an F1 Score of 74.83% and an accuracy of 79.33%.

A learning rate of 0.001 performed significantly worse, suggesting that the network was learning too slowly to reach a good solution within the training limit.

Increasing the learning rate to 0.05 did not improve performance compared to 0.01. Its F1 Score decreased slightly to 73.10%.

This experiment showed that the learning rate has a significant effect on how effectively the network learns, and that 0.01 was the best of the tested values.

### Learning Rate - 0.001

In [9]:
np.random.seed(42)

network = NeuralNetwork(
    input_size=4,
    hidden_size=16,
    learning_rate=0.001
)

losses = network.train(
    X_train,
    y_train,
    epochs=1000,
    print_every=50
)

predictions = network.forward(X_test)
predictions = (predictions >= 0.5).astype(int)

print(f"Accuracy: {accuracy(y_test, predictions) * 100:.2f}%")
print(f"Precision: {precision(y_test, predictions) * 100:.2f}%")
print(f"Recall: {recall(y_test, predictions) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, predictions) * 100:.2f}%")

Epoch 0, loss 0.8232
Epoch 50, loss 0.8021
Epoch 100, loss 0.7826
Epoch 150, loss 0.7644
Epoch 200, loss 0.7475
Epoch 250, loss 0.7317
Epoch 300, loss 0.7170
Epoch 350, loss 0.7034
Epoch 400, loss 0.6906
Epoch 450, loss 0.6786
Epoch 500, loss 0.6674
Epoch 550, loss 0.6569
Converged at epoch 565
Accuracy: 58.66%
Precision: 50.00%
Recall: 48.65%
F1 Score: 49.32%


### Learning Rate - 0.01 (Baseline)

In [10]:
np.random.seed(42)

network = NeuralNetwork(
    input_size=4,
    hidden_size=16,
    learning_rate=0.01
)

losses = network.train(
    X_train,
    y_train,
    epochs=1000,
    print_every=50
)

predictions = network.forward(X_test)
predictions = (predictions >= 0.5).astype(int)

print(f"Accuracy: {accuracy(y_test, predictions) * 100:.2f}%")
print(f"Precision: {precision(y_test, predictions) * 100:.2f}%")
print(f"Recall: {recall(y_test, predictions) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, predictions) * 100:.2f}%")

Epoch 0, loss 0.8232
Epoch 50, loss 0.6671
Epoch 100, loss 0.5872
Epoch 150, loss 0.5431
Epoch 200, loss 0.5169
Epoch 250, loss 0.5003
Converged at epoch 294
Accuracy: 79.33%
Precision: 75.34%
Recall: 74.32%
F1 Score: 74.83%


### Learning Rate - 0.05

In [11]:
np.random.seed(42)

network = NeuralNetwork(
    input_size=4,
    hidden_size=16,
    learning_rate=0.05
)

losses = network.train(
    X_train,
    y_train,
    epochs=1000,
    print_every=50
)

predictions = network.forward(X_test)
predictions = (predictions >= 0.5).astype(int)

print(f"Accuracy: {accuracy(y_test, predictions) * 100:.2f}%")
print(f"Precision: {precision(y_test, predictions) * 100:.2f}%")
print(f"Recall: {recall(y_test, predictions) * 100:.2f}%")
print(f"F1 Score: {f1_score(y_test, predictions) * 100:.2f}%")

Epoch 0, loss 0.8232
Epoch 50, loss 0.4997
Epoch 100, loss 0.4670
Converged at epoch 139
Accuracy: 78.21%
Precision: 74.65%
Recall: 71.62%
F1 Score: 73.10%
